name: Upload to S3

on:
  push:
    branches:
      - main # Change this to your branch if needed

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIAQA2H52WXGKNLTZKR
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://bucket-224466 --exclude ".git/*"

